---
ID: "f8e85291-88ef-436d-a977-346e4a006409"
Parent: "45bf6a6c-f46c-48cc-82a5-a9c13c6667ff"
Template: "f1828a2c-7e5d-4bbd-98ca-320474871548"
Path: /sitecore/media library/Project/AIE/AIE Corporate Site/OurServices/Sitecore Services/Managed Services/Application
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: "-/media/F8E8529188EF436DA977346E4A006409.ashx?h=16&thn=1&w=16"
- ID: "22eac599-f13b-4607-a89d-c091763a467d"
  Hint: Width
  Value: 142
- ID: "40e50ed9-ba07-4702-992e-a912738d32dc"
  Hint: Blob
  BlobID: "0e596908-72bd-4b65-a00d-32eed70badca"
  Value: iVBORw0KGgoAAAANSUhEUgAAAI4AAACGCAMAAAA8cEJXAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAzUExURQAAAP///////////////////////////////////////////////////////////////7eV4oIAAAAQdFJOUwAQIDBAUGBwgI+fr7/P3+8jGoKKAAAACXBIWXMAABcRAAAXEQHKJvM/AAAJ0UlEQVR4Xt1c2ZajMA5tEsjG4vz/1w6ShTbLBjKVzDlzn7ooysjS9ZVkTP/7r9C/5vRWSMvrRr/6PfqZrDCYr/TrH+NmHKPwP3HQtWbN+93TLT9EF0YqI9E9P8RAjw7x+3CN9OQQI930Oyz05BA/j9aFHvxONwVm94Vu+xWYOhNdQEx08efkudNz30+6gHjQxfeDLvwKzOSBLiDYZ7/mMjPZsKSji1/hcjc853l8Rhp7pce+F7pAiK0k9I9pnj7Nsd19WydzOcKNfuWj8qLL7ztdEEjC/YRYnda5V0dXN/Bj3dDM5Rdd2NA96RcAsxoPwVizwjkoZrLisiOPy/6zn94OOlaQDbNhQ03vmMtv/cBrkVHO2XOJUoBSGGbyTBcYTBBZAN0zKEWWE0XaNU5I8xYZIYKnyD/+DRsf14zvdNieijUr4BldP8psizWn6o4Rfhm6BnHUHlPmuain28NMttAkIc+K5dm7mWlKpkNFY6+sSbeGq1Y4EQS0bl+j3dM/EQfsMdYgWVhLSpRi16gS0x2W0zl7dKSyNeu1WlkcJspiURMm4gqvSsCOPbog36xZweWEwRSLRyFZgOwahJkxXauAc5GxZjWTswJDPcAhiO6k5VLbE4RbQTy9OL11lJ4fUc4mdHd7s5nZCqWybffwfTYnICQJpteuZvTizlQkYM0JuhKD7onrlesLvTxXo2Rxx2fGpnccr+ZYdE81ppfr9ZgtGddrJaSyNprDSVAPp5RPIGQucrCB8CMQ3D+DKl/alaFKOV9sBkQJUmN9ApTGu9X5d1B5qC07K0R50hnSnoBa5fsR6ITN5yvsQzg3YZVyvxIulf8Oja/Ud4doK7rh8ZqXtGKZxsewP92LEMe093VIbNurvettaQhIYdMqUGv8aDfBezdNWehKWzLSs+FUCdWx2hSgwlsbWZfkyzyO4zSpLF41SIXqRGssHi06FwQbk8aHSmL9nZuMCi9EACu1WwhJuGE9Qq1TmvpyzIEqizmMBS/y420WQMSZLmhk16RqAUaxjqLBAd2VYwPJXXRBkDcT0qvBVyplAxndvH5AQjQ4xsVSz9Zwf1xBLmXLpczeiTlZgXDHZ5WsG+M+D9FBhT0ssafcIyvdETL75nlkVaCDfXUlTdYZ8rDA+fDjnA8qBs7JD8AScngzs7uKOjiK4BOcNdf7E5LWMr3uLgB4t/OCJOidbALo+rt5neh8jSWuEbjuZjLFZDdY0JdOYJR2v5fxESgX4jo8tMxnOEeApw07b8VfJGMQ/IFbm6rPzViFfbBu7W6TconA0R+cr9XUb2dm6IYR5ct6zGwACXBvKsPvCTFs4sE6Uflra5PT9LwPw+2xsVSnavCFI60Q02Lzq6xqB6cacN8il6hX0j3p1pore+CKZXP9rSVOtW6NWygwjLg0W+O3MWgwiSgkP+eeuj3rOhYBtigafRhYnJPHXIrFmiOo6As/W/aoPXuHlauhc9L0KAoA0HdhDjLAb7oAsp2SkmD8IkFd7iyHBvdi7yyNzz7cFoBp8uOxqovLy1za8p2wkkIFvgTKsihZSnNdldYorHeIKqJznCptQGURh8AD6rXWsOou3J+ReAsl7eyUgNN54SPh1CqzAAOko4Mg7+TLgfnL5uztWAD9OINhsVhxDrmH6Qv37jW/HKLD5gDHmBAYq4DHGSi8HC34qb2L84k58BdsANjWeIRNVesPe9XEZ+bQP/MPjfIS6CIWrMT4e3PMoEC9RoeNsaR/u4nE+H8wRwaFHxqrBVahjPcVc0CsWEuwDqN/B7BMPzD4eXPAAhZX7E+qsokiyUy3ch7jvDlGXFEGfZ5m4G+NZDZWIaI0Z6+HhyTBOoxCV50AOFLqWuB1VcARnbx+QVYSxte93mzYzIwVS8U9WLII0cG4agvdQVukTMC7NZZXJa3DDEzZUHFo3lHieeE0ogF9EwWY4/JrbYCKEcAhkpmRzFFOz+WXiBKMX2hCdy+bKMAjzzOClzmgpEQrbz+XZwWoOBU7g1hV360D4XAdRPDbD/AgoQvtZzr+5KMfqkzESdiB4vYMgM5Hv0dwagFljFpN1G2rwz3dtkmnvAHOseuqPG2ygeJR9KkbbLwwPsobvDmy1rR9v1aZFAJtDTDHOQcTWoAkxKwU9m4gbClV0RW/X9cHhHGVOeeEvFlbF/usXrpagatx4fFmw6ZclrYPBJa45VeEAnrqSp3umw1XNiF9reDbV9SLbUoxLk5Z9ZyrTZTBIJN2SxRZ7xZTnzUE2iK37HEYpxd6u2nXkA08ZZ+KcW7OnhrwZJ3fXOdFvpeyNcQ9bsJZcx2lYqA1XrvEOe2saiFS7UsD34LXkM9jFWcVWOPcTtYO5M/oAiPbs3fcP2tAeXKCWeBTUBviHrogIFVtjUdJKXgpw6KzMx0HSWR0QYNcVzOoe2QfRJvhbE61Aoog0hlWuVv1Fm0N95Su/SGZDIwh4BR3JOdWXLBxK5m97cvwpOcFh2QQzMkzb8VlnVcr6KvaUFvG8fUaJynt0nbOq4Cqrg6pBeDYu2X1qsAilRt5AnHPUTYff7c8bDWFII0779KZPUd1WWZ94IXlZS0EFjRqTVrV1Kyg3oof0p4z50c+gSqG620UI6suYm8L7UPIsg0bHgvh2oGbP4I6A7M7YVWsnRLOMzh+BkZVsoeI9hlUBNriLKuqumv8FxB+tlcLS87x8yOfQFZ7UcAY0E3VYq2rnUsM0V1qd0saagWBU0oY00s+saPeE7bQ3TCJxad5hKNNTvBdZXrQjX7rwFDGVd9N1wSqTacrMVRGcU903xdMrdK7y6dfGf7Ehjog3N41VLJjEpb5RIZQNeghjtlgyh/Ze9trKJRianvid8lxBRXvl6j369qaPeVXisn2lJ/IEEJ7VF1msLUV+mh5XMFqaHsw5Vb3qlYEo1V3rygw7jOMXRh7htonMhmBiOktAY+1OztrjbNHfU8DSHf+pg1RLHjzFUR6iNxl6OH2I5Who2uB3xcMygFFylFLc4LdleCLBsJRa6r28ACyeIqChZ/OJ+71QlI4bo3RKUZSXSXHsyAPG6qeFmjWqc/F1vkXBDatk7RLXjfYr5pV5SZiuZnQhrPHH/3g37o6hJnsxN9R+qw1qz16xZpPZADsf8dlfmyxL6QpvdO+xeChl1IfWOwcl5k65Z/wwaz6t0I7uE/LMo+34K+lMKILBF4CUTE5PKd1uNa3Qh8jpKyy8kMHfApmlokKx7Bdxvw9mMumYGG6fbErChFzORLBn0BYQv+rAoKZ/A26NhFnIkK7e/oGqpka8KW9jwaKF0EaX9kYaqMRra/29xWYotHi1+sKUbPnWAn894jrvL2PBL6IYXQWJSyQP8W/f/8B6ppb6ZPxXbQAAAAASUVORK5CYII=
- ID: "6954b7c7-2487-423f-8600-436cb3b6dc0e"
  Hint: Size
  Value: 2711
- ID: "6f47a0a5-9c94-4b48-abeb-42d38def6054"
  Hint: Mime Type
  Value: image/png
- ID: "c06867fe-9a43-4c7d-b739-48780492d06f"
  Hint: Extension
  Value: png
- ID: "cb09946f-3218-4823-87d2-d5007c199a96"
  Hint: Dimensions
  Value: 142 x 134
- ID: "de2ca9e4-c117-4c8a-a139-1ff4b199d15a"
  Hint: Height
  Value: 134
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191204T115214Z
    - ID: "65885c44-8fcd-4a7f-94f1-ee63703fe193"
      Hint: Alt
      Value: Application
