---
ID: "9c56508e-2882-452c-b14d-a757a9ea8240"
Parent: "45bf6a6c-f46c-48cc-82a5-a9c13c6667ff"
Template: "f1828a2c-7e5d-4bbd-98ca-320474871548"
Path: /sitecore/media library/Project/AIE/AIE Corporate Site/OurServices/Sitecore Services/Managed Services/Deployment
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: "-/media/9C56508E2882452CB14DA757A9EA8240.ashx?h=16&thn=1&w=16"
- ID: "22eac599-f13b-4607-a89d-c091763a467d"
  Hint: Width
  Value: 158
- ID: "40e50ed9-ba07-4702-992e-a912738d32dc"
  Hint: Blob
  BlobID: "935cd899-1d94-4fe8-8448-d0eec5a321b2"
  Value: iVBORw0KGgoAAAANSUhEUgAAAJ4AAABfCAMAAAAu745YAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAzUExURQAAAP///////////////////////////////////////////////////////////////7eV4oIAAAAQdFJOUwAQIDBAUGBwgI+fr7/P3+8jGoKKAAAACXBIWXMAABcRAAAXEQHKJvM/AAADiUlEQVRoQ82b2YKDIAxFS90XZP7/a0draK2i3hBiPY8zDdwmGEOgjyiyomp6a93EMPRdW5c5/evHmLzu3V+Ioa0y+tCPMHkbluZxze+8mDfH2maG5kmfv5Tc0vzndJcLZIibuFZg1tG0OA2Z6mOgNbfGFWSuTITrZi5xYB7juhmrvwKreHVjgLXzdEMTReJ0s3RL08SjqU/ouwnF+FY0hQhnaLTUlDSBkJ6GS8xT8swu0cl/PY0u57P8pmrR2sGOBWwuC3qShTczzCM+a/sVkL6OT9vJQjtRjX4rvrXNRFc2CXLKB1fuVhVxCzOp8w6JerHUZIwT/33G0DMx7MkaE/8s1TQrTEGGMG5c41V0KippWhRuBWrn1BbtQN6LmRvb1qfYLHIFUmYEyckKwy3WtuHt6N6wwssKEgXWE7czcWQNwZmiX787+TlpguO+gWzOWQbWw1saREvGCLA8G0z5Gf713nCiSyanbAJLmIgMSKYIZHFCKLAefkWBl3+GLI4ZDrsU7AyNl1aQvL3AergZOqm8o8ASzAydUh7WfmJlaHTt5fXp1z4LrIeTocnkGFOeh8RV8FOGZ2hLFkeYCkiorL4inKE7MjgAaiD3vM0VmqFPv7NBUikjsB4oQ9uzYTPEdVENYyBDT3uBQ6AsygysBxm7OwwLpK5mB5bAMnS3GxpEnegkAMvQNlyUGiSfxAXWA75BggIRW95magNcwbQbN0CmrM3KFkaBtXIg2O6R9dg59d931wo9Hei2BLsjGf1zyc4J+g7LF3BGf4sh2NZmN2i2LF4ikqMVLXkf//F7ZQvU5L1H5qzZDXry/PPBqrjXKMqbM4UotqryXolWNpamvFfPWbT0dOVN7hMtPV15k/tkJ2e68sYqJKLXtUBX3t/zIXpwteVV95bX3Vuevbc894D2ULsoy/u7dd4b5cmOldXlycZSljeAbe49lOWNNbPo2VCW1wnv+ijLGytmUXSV5U1dnVvu1F68bodJ3BfsbCSTN/ebJe5rMrMh7kA3wNw2keUWPfxWPN1aTsq7UyV78SrxeeyQ7ujVLO9WXXejC+arNyfpoqmwOlW8mb7NKRH39FqVYXsMEHu/SIGAupGkFzIF7P1SIeZ+THre99m2yBpWKTi+RGHkPzKQ4LaHQmuQE3sleugaZPETF7oGv6NZ1OnuzCO4rth/IsIUZd332pF2znZNGfTb4/EP9ghk8oJVZDoAAAAASUVORK5CYII=
- ID: "6954b7c7-2487-423f-8600-436cb3b6dc0e"
  Hint: Size
  Value: 1103
- ID: "6f47a0a5-9c94-4b48-abeb-42d38def6054"
  Hint: Mime Type
  Value: image/png
- ID: "c06867fe-9a43-4c7d-b739-48780492d06f"
  Hint: Extension
  Value: png
- ID: "cb09946f-3218-4823-87d2-d5007c199a96"
  Hint: Dimensions
  Value: 158 x 95
- ID: "de2ca9e4-c117-4c8a-a139-1ff4b199d15a"
  Hint: Height
  Value: 95
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191204T115214Z
    - ID: "65885c44-8fcd-4a7f-94f1-ee63703fe193"
      Hint: Alt
      Value: Deployment
