---
ID: "d4d5340d-9cfa-4df6-9aef-98446c742d14"
Parent: "48a179fb-a3da-4ba0-8144-7b42b01f8a88"
Template: "48a179fb-a3da-4ba0-8144-7b42b01f8a88"
Path: /sitecore/templates/Project/AIE/Settings/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190506T091128Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\virtualssuser
