---
ID: "6b5e597e-3409-4878-b440-53bdb14e9f85"
Parent: "6f9e458e-e573-4696-80f0-913b9d01e2a1"
Template: "26fce9bf-0256-458d-8281-a713a5bf5520"
Path: /sitecore/content/AIE/AIE Corporate Site/Presentation/Cache Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190506T091423Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\virtualssuser
