---
ID: "52696c88-b29a-4e84-a1a3-c1310291c3c8"
Parent: "af3b8dbb-5569-420c-becd-3a0f8461f85c"
Template: "f1828a2c-7e5d-4bbd-98ca-320474871548"
Path: /sitecore/media library/Project/AIE/AIE Corporate Site/Blogs/Content/Sitecore/SXA/Security
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: "-/media/52696C88B29A4E84A1A3C1310291C3C8.ashx?h=16&thn=1&w=16"
- ID: "22eac599-f13b-4607-a89d-c091763a467d"
  Hint: Width
  Value: 112
- ID: "40e50ed9-ba07-4702-992e-a912738d32dc"
  Hint: Blob
  BlobID: "d8a9fb53-2dc4-45f9-b27a-bfa014ec13c3"
  Value: iVBORw0KGgoAAAANSUhEUgAAAHAAAABiCAIAAAAHnMCMAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAfkSURBVHhe7d1ZTBNbGAfwWwq0qIAoEbB1ialoEAwW464vIIoJURRcUNBEhAcKSVU0xgVt1Gi4agjGBV+MoqIhBrcHE1QUIxE3NFCpQUk0CEqj4hKXtPWeG//3Rp127EzPDHQ6vzfCN9855x86a2n/+t7LdHR01NXVHTlypLCwcO7cuWPGjFGr1X/9JzIycsqUKdnZ2SaTqbq62mw2f/78GVv2Dr0iULvdXl9fv3HjxsmTJwcHByM89+h0uvT09KNHj3Z2dqJdj+rhQJ8/f15SUqLX6/38/JAQX1FRUZmZmdeuXUPrHtJjgb58+bK4uDgiIgJ50JOYmHj58mUMI7oeCNThcJSWlg4bNgwBCGP+/PmPHj3CkCISO9Dm5uaUlBQsWmBhYWEHDx7EwGIRNdCKiopBgwZhuWJZtGjR69evMQPhiRfoli1bsETRxcXFkVcG5iEwMQIlO828vDwszm3h4eEJCQnJyclZWVkFBQWrV68mTcgZ0vTp06Ojo5VKJerco9Vq7969iwkJSYxASRZYlhuGDx9uMBguXbr04sULm82GFr96//59Y2PjgQMHkpKSAgICsOWfkM4tLS1oIRjBA921axcW9CczZsyorKx8+/YttnTPgwcP1q5dS44/6MIqNja2q6sLWwpD2EDJH5o7Z+zkaoccr8j1EjbjrrW1dcWKFWjHipxOYRthCBgouQpy52QzJyeH1lH4woULgwcPRl/XysrKsIEABAw0OzsbK3DNZDKhmpKmpqaxY8eiuwvBwcEWiwUb0CZUoLW1tQqFAitwxt/fv7y8HNVUkYvaqVOnYhgXli1bhmraBAmU7A3JBTXm7sKOHTtQLQByhsC+t1Gr1Q0NDaimSpBAb968iYm7sHDhQpQK5saNGyqVCuM5s3LlSpRSJUigq1atwqyd0Wg05FWJUiGxX5uRi2Dyh4xSeugHSk70oqKiMGtnDh06hFKBkVPaUaNGYVRnyKUBSumhHyg592Q5HJHLlY8fP6JUeLt378bAzixevBh19NAPtKioCPN1ZtOmTagTRVtb28CBAzE2AzlwvXv3DqWUUA6UHN9nz56N+TIolcq6ujqUisLhcMyZMwfDMwQEBFC/Y0I50O7ubnK9jPkyREZGWq1WlIqFvCYwvDNnzpxBHSWUAyXX1OHh4ZgsQ0pKiqsbSMKpqqpiuZ9A/ZY+5UCbm5uDgoIwWYYlS5agTkS3bt0KDAzEDBg2b96MOkooB9rS0tK3b19MlqFHAiV7yZ/fKvGbvLw81FEiaqCZmZmoE9G9e/dYAiXXIKijxNcDzc3NRR0lcqByoBzJgVImB0qZHChlcqCUyYFSJgdKmRwoZd4daHt7e79+/TBZhuXLl6NORE+ePGG5X2MwGFBHCZ1ALRbLqVOntm/fvmDBAn9/f0yWYciQIenp6aRGNBkZGUlJSSxv1dPpdEajsaysrKampru7G+vxgKeBXrlyJS0tjeu/bvROJFyTyfTmzRusjRePAmW/Ge6l4uPj79+/jxVyxzNQm83G/vDdq0VERNTX12OpHPEMtKSkBINL1MiRI1+9eoXVcsEn0KdPn7I8m5UMfk9H+ARK9twYU9I0Gg3Xt1MTnAO12+0sT7qlRKFQXL9+Hct2G+dAv379Om3aNIzJQE6hY2JiYr1EXFzc0KFDMXVneDy1pxyoXq+3Wq2fvcfJkycxdWeOHz+OZbuNcqDjx4//8uULSr1BVVUVpu5MzweakJDw4cMHlHqD06dPY+rOyIFyJgdKmRwoZXKglMmBUuZbgZJWtbW1+/fvNxqN+fn5xcXFlZWVra2t+DUNvhJoZ2fnhg0bdDod+v6kf//+ycnJ58+fR6lnfCLQq1evjh49Gh1dKyws9PwiQvqBnjt3juW56W/S0tI8/CcdiQdqsVhCQ0PRyz1k94qNeZFyoHa7PSMjA43cFhgYeOfOHbTgTsqBms1mlncksPDk2bqUAz18+DC6cDRx4kTeRycpB7p+/Xp04YicSPF7oEZIOVBy3o4uHIWEhMiBOnH27Fl04WjSpEnyS96J9vb2AQMGoBEXRUVFaMGdlAMl1qxZg0ZuCwsLa/Hg88IkHmhXV1d0dDR6uWffvn3YmBeJB0o0NDRotVq0+5OCggKHw4EteZF+oMTjx49TU1PZP39Ro9GUlpZiAw/4RKA/LF26FE0ZVCoVj/d0OOVDgRqNRjRl6NOnD/krRp1nfChQsn9EU4agoKCHDx+izjNyoP+SA+WDPdDGxkbUecaHAjUYDGjKoFaraX1GvQ8FunXrVjRlCA0N7ejoQJ1nfCjQpqYmV/ebc3JyPDyf/58PBUqcOHGC+cBu1qxZFD/o37cCJW7fvp2VlaXX62NiYhITE/fs2UMmgN/R4HOB/vDt27dPnz7hB6p8NFDhyIFSJgdKmRwoZXKglMmBUtbbA50wYQLqvMTFixcxdWeOHTuGOrdRDlSr1e7cufNvL7F37172LyypqKjAst3GOVCbzfbHr6WQjOrqaizbbZwDJfLz8zGgpKlUKh4PWvgEWlNTgzElbebMmTy+M4tPoORVP2/ePAwrUUqlkt+3AvMJlGhraxsxYgQGl6Jt27ZhqRzxDJQwm83x8fEYX0IUCoUn3/XEP1DCarXm5uayfDab1xk3bhyPI/vPPAr0h2fPnpWXl6empoaEhGBeXsXPzy82NnbdunVkp8njKPSL79//ARlPYwKzg8LcAAAAAElFTkSuQmCC
- ID: "6954b7c7-2487-423f-8600-436cb3b6dc0e"
  Hint: Size
  Value: 2127
- ID: "6f47a0a5-9c94-4b48-abeb-42d38def6054"
  Hint: Mime Type
  Value: image/png
- ID: "c06867fe-9a43-4c7d-b739-48780492d06f"
  Hint: Extension
  Value: png
- ID: "cb09946f-3218-4823-87d2-d5007c199a96"
  Hint: Dimensions
  Value: 112 x 98
- ID: "de2ca9e4-c117-4c8a-a139-1ff4b199d15a"
  Hint: Height
  Value: 98
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190724T132033Z
    - ID: "65885c44-8fcd-4a7f-94f1-ee63703fe193"
      Hint: Alt
      Value: Security
