---
ID: "d2277b00-7a73-43bf-b2b9-b18a9f8fc2b1"
Parent: "1310df35-9ee0-44bb-aebf-619a708b54ad"
Template: "1310df35-9ee0-44bb-aebf-619a708b54ad"
Path: /sitecore/templates/Project/AIE/Blog/BlogPost/__Standard Values
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: Applications/32x32/text_rich_colored.png
- ID: "24171bf1-c0e1-480e-be76-4c0a1876f916"
  Hint: Page Design
  Value: "{EFD43539-E06D-421D-A942-690BBE52BB30}"
- ID: "c9283d9e-7c29-4419-9c28-5a5c8ff53e84"
  Hint: __Bucketable
  Type: Checkbox
  Value: 1
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{D2933DA8-1530-46D6-90BC-0024F824EDF0}"
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{269BDDC7-E377-4C61-9B26-A00BA2CCD14D}" />
      <d
        id="{0B4A31C9-712D-4578-A396-2DDC0F34B63A}"
        l="{72C595AD-68BB-44BC-B5CD-2A857039515F}" />
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190708T061326Z
    - ID: "3cd43efe-8a96-4f96-9140-654849f0675f"
      Hint: Introduction
      Value: This section is for providing quick info on what is the current blog is all about and what is covers. This information should not be more than 3 lines.
    - ID: "62c4305f-4328-4126-a0c3-657315ad18e6"
      Hint: Blog Title
      Value: $name
    - ID: "9e2ad13b-6212-4baf-b391-af5f6ca84fe9"
      Hint: Blog Image
      Value: |
        <image mediaid="{9336B305-86C2-4D71-9532-E669FBED11CE}" />
    - ID: "b138f795-2f6c-46f7-9903-acb647bbccbf"
      Hint: Author
      Type: tree list
      Value: Blog Author
    - ID: "d48a736f-3a15-4c91-b8f3-47fbc248b441"
      Hint: PublishedOn
      Value: $now
