---
ID: "d1ea5fa6-31d3-4f78-8da1-cea8696831b6"
Parent: "e34e4ee4-2a96-433e-9e9f-8f392ac8e39b"
Template: "fe5dd826-48c6-436d-b87a-7c4210c7413b"
Path: /sitecore/media library/Themes/AIE/AIE Corporate Site/AIEnterprise/sass/base
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 100
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170614T063530Z
