---
ID: "6cd16e30-f302-4360-a8b3-0323e17cdf40"
Parent: "d3856ecf-449f-4daf-8a1c-6f5c24592ce5"
Template: "1310df35-9ee0-44bb-aebf-619a708b54ad"
Path: /sitecore/content/AIE/AIE Corporate Site/Home/blog/2019/07/08/12/38/How to automate the Automation Testing
DB: master
SharedFields:
- ID: "97fb669d-5b8e-4829-9a24-06418c315d73"
  Hint: SxaTags
  Value: 
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190708T123803Z
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: How to automate the Automation Testing
    - ID: "4f441595-f0b8-48fc-8f58-8ceda868003e"
      Hint: Content
      Value: |
        <h4>What is a CMS? - quick definition</h4>
        <p>The modern web content management system&nbsp;is about creating, managing, and optimizing your customers&rsquo; digital experience.</p>
        <p>More specifically, a CMS is a software application that allows users to collaborate in the creation, editing, and production of digital content: web pages, blog posts, etc. The CMS (or WCM&mdash;web content management system) are evolving from just helping you launch digital content to more robust systems that are core to managing an overall digital experience across many different channels, such as email, mobile apps, social media, web sites, and more.</p>
        <p>
        Any basic solution for web content management helps you upload or write content, format it, add headlines and images, and do a number of backstage things like SEO. But in a multi-device, user-centric world, that&rsquo;s not enough. Digital marketing has evolved, focusing more deeply on customer experience while incorporating mobile apps, the Internet of Things, and more. All that depends on a&nbsp;<a href="https://www.sitecore.com/products/sitecore-experience-platform/wcm" style="color: #232323; background: 0px 0px;">web content management system</a>&nbsp;that separates content&nbsp;<em>management</em>&nbsp;from content&nbsp;<em>presentation</em>.
        </p>
        <h4>What&rsquo;s the difference between CMS and WCM?</h4>
        <p>Short answer: Not much.</p>
        <p>The terms &ldquo;content management system&rdquo; and &ldquo;web content management&rdquo; system (WCM or WCMS) are often used interchangeably, and there&rsquo;s no clear industry definition that lets you tell one from the other.</p>
        <p>CMS tends to imply the creation, editing, and management of content, while WCM implies all that, plus management of your websites themselves. But in 2018, whether a vendor prefers one term or the other doesn&rsquo;t tell you what you need to know, so you&rsquo;ve got to look under the hood to see what&rsquo;s really being offered.</p>
        <div class="blog-desc-image"><img height="453" alt="BlogImage" width="695" src="-/media/114490D29B854F09856943B26E76E4C7.ashx" /></div>
        <h4>Key features in a CMS/WCM solution</h4>
        <p>Important capabilities in a content management solution will include:</p>
        <ol>
            <li>
            <p>Content management: How, and how easily, can you create, edit, post, and manage web content (including text, images, video, and audio)?</p>
            </li>
            <li>
            <p>Presentation: Customers jump from device to device, and no marketing org can put human effort into optimizing every blog post or catalog page for laptop, tablet, and top smart phone formats. You want to create it once and have the CMS automate the presentation to suit the device.</p>
            </li>
            <li>
            <p>Integration: Is the solution holistic , like Sitecore&rsquo;s Experience Platform, or does it rely on APIs to connect your content to other applications, such as CRM and ERP tools, and to crucial external platforms such as Facebook? Are the APIs you&rsquo;re going to need available?</p>
            </li>
            <li>
            <p>
            Commerce: A crucial integration is being able to connect a personalized marketing presentation to your&nbsp;<a href="https://www.sitecore.com/products/sitecore-commerce" style="color: #232323; background: 0px 0px;">digital commerce systems</a>. You can&rsquo;t address the &ldquo;customer journey&rdquo; if you leave this destination off your map.
            </p>
            </li>
            <li>
            <p>Personalization: Can it target relevant content to unique visitors, by persona, location, or even individually based on past interaction with your brand?</p>
            </li>
            <li>
            <p>Analytics: You&rsquo;re serving up content, but is anyone reading it? And what do they do next? Demand visibility into performance so you can optimize your efforts and define ROI.</p>
            </li>
            <li>
            <p>Governance: Can you find stuff after you post it? Can you strictly control who&rsquo;s allowed to approve it, change it, publish it, take it down? Can you tell when content has aged out of usefulness?</p>
            </li>
            <li>
            <p>Multilingual support: Are you translating into other languages and publishing globally? Can the solution support that?</p>
            </li>
            <li>
            <p>Scalability/Performance/Stability: Is the solution reliable from a fundamental technology standpoint, and will it grow with your organization&rsquo;s needs?</p>
            </li>
            <li>
            <p>Training/vendor support: WCM solutions are increasingly complex, with ever-greater promises, but most teams need help to get up and running beyond a basic level.</p>
            </li>
        </ol>
    - ID: "62c4305f-4328-4126-a0c3-657315ad18e6"
      Hint: Blog Title
      Value: How to automate the Automation Testing
    - ID: "b138f795-2f6c-46f7-9903-acb647bbccbf"
      Hint: Author
      Value: "{F613C6C0-2954-42CB-95D8-65DAF60BEEEF}"
    - ID: "bb6835c4-82af-4d11-9102-a61694c17055"
      Hint: Title
      Value: How to automate the Automation Testing
    - ID: "d48a736f-3a15-4c91-b8f3-47fbc248b441"
      Hint: PublishedOn
      Value: 20190708T123803Z
